experiment:
  name: dataset_IBD_case
  dataset: "D:/common/document/GitHub/mbddpm/data/demo_IBD_case.csv"  # you need change dataset abs_path
  seed: 42

data:
  batch_size: 16  # 16

model:
  num_time_steps: 1000  # 1000
  add_method: code  # code

training:
  num_epochs: 150000 #
  lr: 0.00001  # 0.00001
  ema_decay: 0.9999 # 0.9999
  save_epoch: 150000 # num_epochs

sampling:
  checkpoint: "D:/common/document/GitHub/mbddpm/checkpoint/dataset_IBD_case/epoch_150000_dataset_IBD_case_code.pt"
  # you need change checkpoint abs_path
  generate_num: 1000  # 1000

device: "cuda:0"