experiment:
  name: dataset_case_first10_08030300
  dataset: "D:/common/document/GitHub/mbddpm/data/demo_case_first10.csv"
  seed: 42


data:
  batch_size: 16  # 16

model:
  num_time_steps: 1000  # 1000
  add_method: code  # code

training:
  num_epochs: 100 # recommended ≥ 150000 iterations for stable convergence
  lr: 0.00001  # 0.00001
  ema_decay: 0.9999 # 0.9999
  save_epoch: 50 # num_epochs

sampling:
  checkpoint: "D:/common/document/GitHub/mbddpm/checkpoint/dataset_case_first10_08030010/epoch_100_dataset_case_first10_08030010_code.pt"
  generate_num: 100  # 1000

device: cuda