experiment:
  name: mbddpm_demo
  seed: 42

data:
  batch_size: 16

model:
  num_time_steps: 1000
  add_method: code

training:
  num_epochs: 10000
  lr: 0.00001
  ema_decay: 0.9999
  save_epoch: 5000

sampling:
  generate_num: 1000

device: cuda